/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jcyh_mysmartx_http_MyServerJNI */

#ifndef _Included_cn_jcyh_eaglelock_http_MyServerJNI
#define _Included_cn_jcyh_eaglelock_http_MyServerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jcyh_mysmartx_http_MyServerJNI
 * Method:    getServerUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_jcyh_eaglelock_http_MyServerJNI_getServerUrl
  (JNIEnv *, jclass);

/*
 * Class:     cn_jcyh_mysmartx_http_MyServerJNI
 * Method:    getServerKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_jcyh_eaglelock_http_MyServerJNI_getServerKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
