/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jcyh_mysmartx_http_MyServerJNI */

#ifndef _Included_cn_jcyh_eaglelock_http_MyServerJNI
#define _Included_cn_jcyh_eaglelock_http_MyServerJNI
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jstring JNICALL Java_cn_jcyh_eaglelock_http_MyServerJNI_getServerUrl
  (JNIEnv * env, jclass jobj){
            return (*env)->NewStringUTF(env,"http://119.23.58.28:8083/");
  }

JNIEXPORT jstring JNICALL Java_cn_jcyh_eaglelock_http_MyServerJNI_getServerKey
  (JNIEnv * env, jclass jobj){
    return (*env)->NewStringUTF(env,"Eagleking9");
  }

#ifdef __cplusplus
}
#endif
#endif
